steps:
- name: 'gcr.io/cloud-builders/docker'
  env: ['DOCKER_BUILDKIT=1']
  args: [ 'build', '--build-arg', 'jetbrains_container_id=registry.jetbrains.team/p/prj/containers/projector-idea-c:latest', '-t', 'gcr.io/jetbrains-vertexai-ides/github.com/gclouduniverse/vertexainotebooks-idea-c:$COMMIT_SHA', '.' ]